name: deepdame
description: "An online checkers game"

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ^3.10.4

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
    min_sdk_android: 21

dependencies:
  chat_bubbles: ^1.7.0
  stomp_dart_client: ^3.0.1
  flutter_svg: ^2.0.10
  google_fonts: 6.3.3
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  http: ^1.6.0
  web_socket_channel: ^3.0.0

  flutter:
    sdk: flutter
  uuid: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0

flutter:

  assets:
  #Fonts:
  #Lora font
    - assets/fonts/Lora/static/Lora-Bold.ttf
    - assets/fonts/Lora/static/Lora-Medium.ttf
    - assets/fonts/Lora/static/Lora-Regular.ttf

  #Nunito font
    - assets/fonts/Nunito/static/Nunito-Bold.ttf
    - assets/fonts/Nunito/static/Nunito-Medium.ttf
    - assets/fonts/Nunito/static/Nunito-Regular.ttf

  #Vectors:
  #Cross-hatching 
    - assets/vectors/CrossHatchFade.svg

  #Board
    - assets/vectors/Board.svg

  uses-material-design: true